version: 2.1

orbs:
  codecov: codecov/codecov@1.2.5

executors:
  ubuntu:
    machine:
      image: "ubuntu-2004:202010-01"
    working_directory: /home/circleci/go/src/github.com/geckoboard/sql-dataset
    environment:
      GOPATH: "/home/circleci/go"

commands:
  install_go:
    description: "Exports go bin path and installs specific go version"
    steps:
      - run: echo 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
      - run:
          name: "Remove old go directory"
          command: sudo rm -rf /usr/local/go
      - run:
          name: "Upgrade go to 1.16"
          command: |
            cd $HOME
            curl https://dl.google.com/go/go1.16.7.linux-amd64.tar.gz -o golang.tar.gz
            sudo tar -C /usr/local -xzf golang.tar.gz

jobs:
  test:
    executor: ubuntu
    steps:
      - install_go
      - checkout
      - run: make pull-docker-images run-containers
      - run: make setup-db
      - run: make test
      - codecov/upload
  build:
    executor: ubuntu
    steps:
      - install_go
      - checkout
      - run: make build
      - store_artifacts:
          path: builds
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
